#ifndef KEYPRESS_H
#define KEYPRESS_H

#include "exactint.h"


enum Keypress_Values 
{
    /* keypad digits (these must be 0-9 */
    key_0=0, key_1, key_2, key_3, key_4, key_5, key_6, key_7, key_8, key_9, /*key_A, key_B, key_C, key_D, key_E, key_F,*/ key_star,key_pound,key_pause,key_ok,key_backspace,key_increment,key_decrement,
    key_scroll_up, key_scroll_dn, key_close, key_delete_value,
    /* arming related keys */
    key_arm, key_arm_dw, key_arm_motions, key_arm_all, key_disarm, key_status_settings, key_dealer_icon, 
    key_emergency,key_alert, key_weather, key_thermostat, /*key_cancel, */key_bypass, key_ac, key_battery, key_instant, /*key_silent,*/
    key_offLine_nu,key_cancel_bypass,key_exit_delay_off,key_exit_delay_on,key_silent_on,key_silent_off, 

    /* dealer contact keys */
    /*key_dealer_contact_close,*/ key_customer_service, key_billing, key_techsupport, key_reqsent, key_banner, /*key_banner_invis,*/

    /* dealer promo keys */
    key_ad,

    /* home status icons are handled as disabled controls */
    //key_door_status_open, key_door_status_closed, key_window_status_open, key_windows_status_closed,
    //key_status_occupied, key_status_unoccupied, key_status_armed, key_status_disarmed,

    /* settings screen  keypresses */
    key_alrm_hist, key_panel_status, key_motion_chime_on, key_motion_chime_off, key_chime_on, key_chime_off, key_lights_on,
    key_lights_off, key_volume_up,key_volume_dn, key_beep_volume_up, key_beep_volume_dn,
    /*key_contrast_up,key_contrast_dn,*/ key_calibration, /*key_lang,*/ key_brightness_up,
    key_brightness_dn, /*key_scroll,*/ key_scn_main, key_scn_blank,
    key_enroll, key_clearhistory, key_locks, key_lights, key_quick_exit_b, key_use_pw_yes, 
    key_use_pw_no,

    /* thermostat screen */
    /*key_tstat_emergency,*/key_tstat_ok, key_tstat_1, key_tstat_2, key_tstat_3, key_tstat_up, 
    key_tstat_down, key_tstat_run, key_tstat_hold, key_tstat_heat, key_tstat_off, key_tstat_ac, key_tstat_on, key_tstat_auto,
    /*key_tstat_return,*/

    /* calibration screen keypresses */
    key_cal_upper_right,key_cal_lower_right,key_cal_upper_left,key_cal_lower_left,
    /*key_cal_center,key_cal_emergency, key_cal_cancel,*/

    /* weather screen */
    //key_weather_close, key_weather_emergency,

    key_main_blank,

    /* key internal generated by the system must start with key_pseudo_.... */
    key_pseudo_keypad,          // => keypad display requested

    /* Emergency screen */
    key_emergency_fire, key_emergency_police, key_emergency_aux,

    /* Main doors, windows, motion buttons*/
    key_doors, key_windows, key_motion, key_property /*key_sensors*/,

    /* light control screen - do not change the order of the keys as it will affect light_screen.c control */
    key_light_on_1, key_light_off_1,    key_light_on_2, key_light_off_2,   key_light_on_3, key_light_off_3,   key_light_on_4, key_light_off_4,
    key_light_on_5, key_light_off_5,   key_light_on_6, key_light_off_6,   key_light_on_7, key_light_off_7,   key_light_on_8, key_light_off_8,
    key_light_on_all, key_light_off_all, 
    /* doorlock control screen - do not change the order of the keys as it will affect doorlock_screen.c control */
    key_doorlock_lock_1, key_doorlock_unlock_1,    key_doorlock_lock_2, key_doorlock_unlock_2,   key_doorlock_lock_3, key_doorlock_unlock_3,   key_doorlock_lock_4, key_doorlock_unlock_4,
    /*key_doorlock_lock_5, key_doorlock_unlock_5,   key_doorlock_lock_6, key_doorlock_unlock_6,   key_doorlock_lock_7, key_doorlock_unlock_7,   key_doorlock_lock_8, key_doorlock_unlock_8,*/
    key_doorlock_lock_all, key_doorlock_unlock_all,
    /* system information screen */
    key_faq, key_help, 

    /* system help screen */
    key_help_button_1, key_help_button_2, key_help_button_3, key_help_button_4, key_help_button_5, key_help_button_6, key_help_button_7, key_help_button_8,

    /* advertisement screen ... Note: 1) these must be sequential in oder*/
    /*                                2) must have same number of ids as MAX_PROMO_ADS */
    key_ad_1, key_ad_2, key_ad_3, key_ad_4, key_ad_5, key_ad_6, key_ad_7, key_ad_8, key_ad_9,
    key_ad_10, key_ad_11, key_ad_12, key_close_ad,

    key_programming,
    
    key_clear,
    key_bars,
    key_generic_2,
    
    //I am trying to force these to be at the end of the list.  Values above 0xFF are legal, but it seems an enumeration of this type
    //cannot hold a value above 0xFF.  These place holders are for screens to use as their screen specific controls.
    key_place_holder_0 = 0xCD, key_place_holder_1, key_place_holder_2, key_place_holder_3, key_place_holder_4,
    key_place_holder_5, key_place_holder_6, key_place_holder_7, key_place_holder_8, key_place_holder_9,
    key_place_holder_10, key_place_holder_11, key_place_holder_12, key_place_holder_13, key_place_holder_14,
    key_place_holder_15, key_place_holder_16, key_place_holder_17, key_place_holder_18, key_place_holder_19,
    key_place_holder_20, key_place_holder_21, key_place_holder_22, key_place_holder_23, key_place_holder_24,
    key_place_holder_25, key_place_holder_26, key_place_holder_27, key_place_holder_28, key_place_holder_29,
    key_place_holder_30, key_place_holder_31, key_place_holder_32, key_place_holder_33, key_place_holder_34,
    key_place_holder_35, key_place_holder_36, key_place_holder_37, key_place_holder_38, key_place_holder_39,
    key_place_holder_40, key_place_holder_41, key_place_holder_42, key_place_holder_43, key_place_holder_44,
    key_place_holder_45, key_place_holder_46, key_place_holder_47, key_place_holder_48, key_place_holder_49 = 0xFF,
    
    key_return=0xFFFE,
    key_not=0xFFFF,
}; 
#endif
